VERSION_YEAR = 2024
VERSION_MONTH = int('02')
VERSION_DAY = int('27')
VERSION_HOUR = int('15')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 0
MINOR_VERSION = 1
PATCH_VERSION = 202402271500
version_date = '2024/02/27 15:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
